kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-sspengine 
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.1.72
    path: /var/nfsshare/b2bi-env1/ssp/engine

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-sspengine
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: pv-sspengine
  volumeMode: Filesystem
