# Default values for ibm-ssp-cm chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


image:
  # set full path with image name
  repository: image-registry.openshift-image-registry.svc:5000/b2bi-env1/ssp_cm_6011_02
  # set image tag
  tag: 6.0.1.1.02
  # Create image secret and set the image secret name below. 
  imageSecrets: default-dockercfg-wspb7
  # image pull policy 
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""
arch: "amd64"


cmArgs:
  # User UID map between the processes running inside a container and the host system.
  appUserUid: 1000
  # User GID map between the processes running inside a container and the host system.
  appUserGid: 1000
   # Set the value "true" to Generate Key Certificate, if you are installing Secure Proxy CM first and 
   # supply the following key certificate details: keyCertFileName, keyCertAliasName, 
   # keyCertStorePassphrase(secret) and keyCertEncryptPassphrase(secret)
   # Set the value "false" to Import Key Cert Exported from Secure Proxy Engine if you have installed Secure Proxy Engine first and
   # supply the following key certificate details: keyCertFileName and keyCertEncryptPassphrase(secret)  
  keyCertExport: true
  # Set the certificate file name (The certificate file generates inside the installation directory)
  keyCertFileName: "defkeyCert.txt"
  # Set the certificate alias value. 
  keyCertAliasName: "keycert"
  # JVM max heap size - don't set more than container limit resource memory. 
  maxHeapSize: "2048m"
  

# persistence section specifies persistence settings which apply to the whole chart
persistentVolume:
  enabled: true
  # If we want to use any specific PV to bind with PVC then provide PV label name and value else it would be bind with any available PV.
  # Default value is mentioned the below.
  labelName: "app.kubernetes.io/name"
  labelValue: "ibm-ssp-cm-pv-name"
  # useDynamicProvisioning is whether or not to use Storage Classes to dynamically create Persistent Volumes 
  useDynamicProvisioning: false
  size: 2Gi
  accessMode: "ReadWriteOnce"
  

# Service
service:
  # Set the service type.
  type: "LoadBalancer"
  # Add external IP to access application outside the cluster using the IP mentioned below. 
  externalIP: ""
  jetty: 
    # CM web application is accessed by using below mentioned service port, so add as per the requirement else it would be set 8443 as default port. 
    servicePort: 8443
    # If traditional jetty port is different from 8443 while migrating from traditional to container environment then in this case 
    # we need to change container port as traditional jetty port value else It is not required to change the container port value.     
    containerPort: 8443
  cm: 
    # CM is listen on the below mentioned service port, so add as per the requirement else it would be set 62366 as default port. 
    servicePort: 62366
    # If traditional CM listen port is different from 62366 while migrating from traditional to container environment then in this case 
    # we need to change container port as traditional CM listen port value else It is not required to change the container port value.   
    containerPort: 62366
  

# Secret 
secret:
  # create secret and set the secret name below 
  secretName: secret-sspcm 

  
# Use existing service account or manage by helm chart.
serviceAccount:
  # true - Manage by helm chart
  # false - manage by deployment user. If you are changing from true to false then in this case you need to provide service account name.
  # recommended to use true value.  
  create: true
  name: ""


## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
## Container CPU -  limit and request both are set 1 CPU(1000m) as default value but we can modify as per the requirement.
## Container Memory - limit and request both are set 2 GB as default value but we can modify as per the requirement.
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 1000m
    memory: 2Gi

affinity:
  # https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity-beta-feature
  # The matchExpression for key 'kubernetes.io/arch' is automatically added based on
  # architecture preference specified in 'arch'
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution: []
  #    nodeSelectorTerms:
  #    - matchExpressions:
  #      - key: kubernetes.io/e2e-az-name
  #        operator: In
  #        values:
  #        - e2e-az1
  #        - e2e-az2
# The matchExpression for key 'kubernetes.io/arch' is automatically added based on
# architecture preference specified in 'arch'
    preferredDuringSchedulingIgnoredDuringExecution: []

  podAffinity:
    requiredDuringSchedulingIgnoredDuringExecution: []
    preferredDuringSchedulingIgnoredDuringExecution: []

  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution: []
    preferredDuringSchedulingIgnoredDuringExecution: []

# liveness and readiness Probe
livenessProbe:
  initialDelaySeconds: 200
  timeoutSeconds: 30
  periodSeconds: 60
  failureThreshold: 10

readinessProbe:
  initialDelaySeconds: 190
  timeoutSeconds: 5
  periodSeconds: 60
  failureThreshold: 10

 # OpenShift route can be enabled by changing value from false to true. 
route:
  enabled: false
  
# The following files can be customized using key value pair in the list format.
# conf/log4j.properties, bin/log.properties, bin/security.properties, bin/vendor.properties 
# Add/Update: Key and Value both must be provided in the below format.
# <File Name Without Extension>_<Property Name>=<Property Value>
customProperties: []
# below is the example: 
#customProperties:
#  - log4j_log4j.logger.org.apache.commons.beanutils=OFF
#  - log_audit.log.maxfilesize=10MB


# Add/Update VM arguments in the list format
# <Key as Java property name>=<value>
vmArguments: []
# below is the example: 
#vmArguments:
#  - Dssp.cm.jetty.sni.enable=false
#  - DvalidateThruXSD=false
#  - DsspcmDisableClientEndpointIdentification=true


# Use custom common certificate. It updates the engine, CM, and web server certificate. 
# Exports the common certificate configuration into the PV mapped directory.
# Exported certificate(commonKeyCertFile) can be imported into the Engine.
# set the value "true" to update the custom certificate.
# set the value "false" to not update the custom certificate.  
customCertificate:
  customCertEnabled: false
  # set key store certificate file name
  commonCertFile: ""
  # set alias name
  commonCertAlias: ""
  # set export key certificate file name and it can be imported into the Engine.
  commonKeyCertFile: ""
# below is the example: 
#customCertificate:
#  customCertEnabled: true
#  commonCertFile: "commonKeyStore.p12"
#  commonCertAlias: "commonCert"
#  commonKeyCertFile: "commonDefKeyCert.txt"


# The custom directories/files can be mapped using the list format.
# For mapping, We need to provide full path of the file or directory. 
# First we need to create the directory with 'CM_RESOURCES' name if it is not available into PV. 
# and keep the custom directories/files into created directory. 
customFiles: []
# In the below example we need to keep log4j2.xml file inside 'CM_RESOURCES' directory.
# so that the container will copy this file into respective directory.   
#customFiles:
#  - /conf/log4j2.xml


